version: '3'

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'     # HTTP Traffic
      - '81:81'     # Admin Web UI
      - '443:443'   # HTTPS Traffic
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
      DB_MYSQL_NAME: "npm"
    depends_on:
      - npm-db
    networks:
      - npm_network

  npm-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
    volumes:
      - npm_db_data:/var/lib/mysql
    networks:
      - npm_network

  tailscale:
    build:
      context: ./tailscale
      dockerfile: Dockerfile
    container_name: tailscale
    privileged: true
    volumes:
      - /var/run/tailscale:/var/run/tailscale
      - tailscale_state:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
    networks:
      - npm_network

volumes:
  npm_data:
  npm_letsencrypt:
  npm_db_data:
  tailscale_state:

networks:
  npm_network:
    driver: bridge