version: '3'

services:
  npm:
    build:
      context: ./npm
      dockerfile: Dockerfile
    container_name: npm
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
      - /var/run/tailscale:/var/run/tailscale
      - tailscale_npm:/var/lib/tailscale
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
      DB_MYSQL_NAME: "npm"
      TAILSCALE_AUTH_KEY: "${TAILSCALE_AUTH_KEY}"
    depends_on:
      - npm-db
    networks:
      - npm_network

  npm-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
    volumes:
      - npm_db_data:/var/lib/mysql
    networks:
      - npm_network

volumes:
  npm_data:
  npm_letsencrypt:
  npm_db_data:
  tailscale_npm:

networks:
  npm_network:
    driver: bridge